### ISSUE TITLE
Infer `source-paths` and `test-paths`

### ISSUE THREAD

**Issue by vemv** [clj-kondo/lein-clj-kondo#2]
Hi there!

Nice addition of a Lein plugin, however the feature I'd expect the most isn't there: source-paths and test-paths inference.

I consider a traditional weak point in clj-kondo that one has to specify `src` by hand. People would often forget/procastinate adding `test`, or would be unaware of additional paths.

Following the design of many other plugins, source-paths and test-paths should be just grabbed from the `project` and passed to clj-kondo main.

Unless of course something else was explicitly provided as CLI arguments.

I tried `$classpath` btw, it does what it says in the tin, however that would mean that 3rd party deps are also linted - easily failing a build.

Cheers - V

**Comment by ericdallo** [comment]
yeah, makes sense, to be honest I created this plugin before having clojure-lsp available as CLI/API, I do think this feature makes sense for lein-clj-kondo, but clojure-lsp may be a better fit for you since it resolves the source-paths automatically from classpath besides having extra optional linters like unused-public-var.

**Comment by vemv** [comment]
Yeah, definitely there are quite a few ways of running clj-kondo :)

I think lein-clj-kondo has its place in the universe - for example sometimes I want to create a minimal setup or PR without requiring people to learn a whole lot of things

**Comment by vemv** [comment]
PR welcome?

**Comment by ericdallo** [comment]
Sure @vemv, I can't work on that right now, so feel free to open a PR!
