### ISSUE TITLE
Global configuration as resource

### ISSUE THREAD

**Issue by vemv** [clj-kondo/lein-clj-kondo#8]
Hey there,

for a particular scenario I'd like to have a clj-kondo config released as a resource in a .jar and consumed from lein-clj-kondo.

The use case is definining org-wide preferences, etc.

I wonder if this is something that is possible OOTB already, or would it need some hacking?

The main feature/constraint is that the config should be a resource, not a file.

Maybe one could specify this as a Lein plugin option? `{:config-resources ["mega/corp/clj_kondo_config.edn"]}` which the plugin would convert into an `io/resource` call, slurp it, and pass that edn as https://github.com/clj-kondo/clj-kondo/blob/ab3172541dd07e52486962c762c6bd739ab25a09/src/clj_kondo/main.clj#L41-L42

WDYT?

**Comment by borkdude** [comment]
@vemv You can do this by adding the config to a dependency in `resources/clj-kondo.exports/your.org/your.lib/config.edn`. When you then add this dependency to the classpath, and call `lein clj-kondo --skip-lint --dependencies --copy-configs` it should copy the configuration in your `.clj-kondo` dir and then clj-kondo should pick up on it.

Just make sure that library with exported config isn't used by anyone else, since exported configs should normally be just be about one specific library.

**Comment by vemv** [comment]
Nice!

Got it, thanks

**Comment by borkdude** [comment]
I'm fine with this, as long as it doesn't raise the expectation that "vanilla" clj-kondo supports reading configs from project.clj.

**Comment by vemv** [comment]
Yes, I had heard of monorepo niceties, however I'm using a polyrepo in this scenario

**Comment by borkdude** [comment]
OK, even if you have polyrepos it works, as long as the directory structure matches. If the directory doesn't exist, then it won't crash, but it will just not include the config.
